# Generated by Django 3.2.4 on 2021-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_location_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
    ]
