# Generated by Django 3.2.4 on 2021-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
